---
logs:
  level: DEBUG
  token: ~
heudiconv:
  appId: urrutia-heudiconv-0.11.4
  batchQueue: corralextra
  name: heudiconv_test
  archive: true
  archivePath: testing/actor-heudiconv
  maxRunTime: "19:59:00"
  parameters:
    FILES: norshore/bids/1
    LIST_OF_SUBJECTS: sub-01
    OUTDIR: '.'
    SESSION_FOR_LONGITUDINAL: session1
    BIDS: true
    BIND_DIR: /corral-secure/projects/A2CPS/
    HEURISTIC: a2cps.py
    LOCATOR: =''
    SITE: ""
    DELETE_DUPLICATES: true
    POST: "--post"

  notifications:
    -
      event: FINISHED
      url: a2cps-dirc-notify-ui@a2cps.org
pipelines:
  fmriprep_alias: fmriprep.prod
  api_server: https://portals-api.tacc.utexas.edu
  mriqc_alias: mriqc.prod
  vbr_actor_alias: vbr-actor.prod
  heudiconv_alias: heudiconv_router.prod
  qsiprep_alias: qsiprep.prod
  cat_alias: cat.prod
  qaphantom_alias: qaphantom.prod
